import { FormioOptions } from "@formio/angular";

export const options: FormioOptions = {
  i18n: {
    ar: {
      'Label': 'ملصق',
      'Label Position': 'موضع التسمية',
      'Placeholder': 'عنصر نائب',
      'Description': 'وصف',
      'Tooltip': 'تلميح',
      'Prefix': 'بادئة',
      'Suffix': 'لاحقة',
      'Widget': 'القطعة',
      'Input Mask': 'قناع الإدخال',
      'Custom CSS Class': 'فئة CSS مخصصة',
      'Tab Index': 'فهرس علامات التبويب',
      'Hidden': 'مختفي',
      'Hide Label': 'إخفاء التسمية',
      'Show Word Counter': 'إظهار عداد الكلمات',
      'Show Character Counter': 'إظهار عداد الأحرف',
      'Hide Input': 'إخفاء الإدخال',
      'Excellent': 'ممتاز',
      'Initial Focus': 'التركيز الأولي',
      'Allow Spellcheck': 'السماح بالتدقيق الإملائي',
      'Disabled': 'عاجز',
      'Table View': 'عرض جدول',
      'Modal Edit': 'تعديل مشروط',
      'Multiple Values': 'قيم متعددة',
      'Persistent': 'مثابر',
      'Input Format': 'نمط الإدخال',
      'Protected': 'محمي',
      'Database Index': 'فهرس قاعدة البيانات',
      'Mixed (Allow upper and lower case)': 'مختلط (السماح بالأحرف الكبيرة والصغيرة)',
      'Uppercase': 'الأحرف الكبيرة',
      'Lowercase': 'أحرف صغيرة',
      'Encrypted (Enterprise Only)': 'مشفر (مؤسسي فقط)',
      'Default Value': 'القيمة الافتراضية',
      'Drag and Drop a form component': 'قم بسحب مكون نموذج وإسقاطه',
      'Text Field': 'حقل النص',
      'Email': 'بريد إلكتروني',
      'Text Area': 'منطقة النص',
      'Panel': 'لوحة',
      'Time': 'وقت',
      'Submit': 'يُقدِّم',
      'Basic': 'أساسي',
      'Layout Components': 'مكونات التخطيط',
      'Advanced': 'متقدم',
      'Premium': 'غالي',
      'Component': 'عنصر',
      'Display': 'عرض',
      'Data': 'بيانات',
      'Validation': 'تصديق',
      'API': 'API',
      'Conditional': 'الشرط',
      'Logic': 'منطق',
      'Layout': 'تَخطِيط',
      'Allow Multiple Masks': 'السماح بأقنعة متعددة',
      'Input Field': 'حقل الادخال',
      'Top': 'قمة',
      'Left (Left-aligned)': 'يسار (محاذاة إلى اليسار)',
      'Input Type': 'نوع الإدخال',
      'Collapsible': 'انهيار',
      'Preview': 'معاينة',
      'Text Case': 'حالة النص',
      'Redraw On': 'إعادة رسم',
      'Clear Value When Hidden': 'قيمة واضحة عند إخفاءها',
      'Custom Default Value': 'قيمة افتراضية مخصصة',
      'Calculated Value': 'القيمة المحسوبة',
      'Calculate Value on server': 'حساب القيمة على الخادم',
      'Allow Manual Override of Calculated Value': 'السماح بالتجاوز اليدوي للقيمة المحسوبة',
      'Server': 'الخادم',
      'Client': 'عميل',
      'None': 'لا أحد',
      'Validate On': 'تحقق في',
      'Required': 'مطلوب',
      'Unique': 'فريد',
      'Minimum Length': 'الطول الأدنى',
      'Maximum Length': 'الحد الأقصى لطول',
      'Minimum Word Length': 'الحد الأدنى لطول الكلمة',
      'Maximum Word Length': 'أقصى طول للكلمة',
      'Regular Expression Pattern': 'نمط التعبير العادي',
      'Error Label': 'تسمية الخطأ',
      'Custom Error Message': 'رسالة خطأ مخصصة',
      'Custom Validation': 'التحقق المخصص',
      'JSONLogic Validation': 'التحقق من JSONLogic',
      'Property Name': 'اسم الخاصية',
      'Field Tags': 'العلامات الميدانية',
      'Custom Properties': 'خصائص مخصصة',
      'Add Another': 'أضف آخر',
      'Save': 'يحفظ',
      'Cancel': 'يلغي',
      'Remove': 'يزيل',
      'Rows': 'صفوف',
      'Title': 'عنوان',
      'Theme': 'سمة',
      'Data Format': 'تنسيق البيانات',
      'Advanced Logic': 'المنطق المتقدم',
      'Advanced Conditions': 'الشروط المتقدمة',
      'Simple': 'بسيط',
      'HTML Attributes': 'سمات HTML',
      'PDF Overlay': 'تراكب PDF',
      'Number': 'رقم',
      'Use Thousands Separator': 'استخدم فاصل الآلاف',
      'Phone Number': 'رقم التليفون',
      'Url': 'عنوان Url',
      'Date/ Time': 'التاريخ / الوقت',
      'Currency': 'عملة',
      'Signature': 'إمضاء',
      'Survey': 'استطلاع',
      'Day': 'يوم',
      'Month': 'شهر',
      'Year': 'سنة',
      'January': 'يناير',
      'February': 'فبراير',
      'March': 'يمشي',
      'April': 'أبريل',
      'May': 'يمكن',
      'June': 'يونيو',
      'July': 'يوليو',
      'August': 'أغسطس',
      'September': 'سبتمبر',
      'October': 'اكتوبر',
      'November': 'نوفمبر',
      'December': 'ديسمبر',
      'Password': 'كلمة المرور',
      'Select': 'يختار'
    }
  }
};